# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${oc.env:PROJECT_DIR, ./}/submodules/text_recognition_lightning/
target_src: submodules.text_recognition_lightning.src

# path to data directory
data_dir: ${paths.root_dir}/ndldata/

# path to logging directory
log_dir: ${paths.root_dir}/logs/

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
# output_dir: ${hydra:runtime.output_dir}
output_dir: null

# path to working directory
# work_dir: ${hydra:runtime.cwd}
work_dir: null
