# @package _global_

defaults:
  - _self_
  - datamodule: ndl_cli.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: ctc.yaml
  - callbacks: 
    - rich_progress_bar.yaml
    - measure_time.yaml
  - logger: null
  - trainer: default.yaml
  - paths: cli.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ${paths.root_dir}/model/resnet-orient2.ckpt
task: "xml"
