# @package _global_

defaults:
  - _self_
  - datamodule: ndl_rf.yaml
  - model: randomforest.yaml
  - logger: csv.yaml
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

# task_name: "eval"
task_name: ???

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
target:
  - ???
