_target_: ${paths.target_src}.datamodules.mj_datamodule.MJDataModule

data_dir: ${paths.data_dir} # data_dir is specified in config.yaml
label_as_str: True
batch_size: 128
train_val_test_split: [55_000, 5_000, 10_000]
num_workers: 1
pin_memory: True
batch_max_length: 40
