_target_: ${paths.target_src}.datamodules.xml_datamodule.NDLDataModule

dataset:
  train:
  val:
  test:
  pred:

batch_size: 128
num_workers: 16
pin_memory: True
batch_max_length: 40
test_batch_max_length: 160
test_max_width: 1600
character_file: ${model.character_file}
additional_elements:
  - BLOCK[@TYPE="ノンブル"]
  - BLOCK[@TYPE="柱"]
